### ISSUE TITLE
point number format (1000.00 => 1.000,00)

### ISSUE THREAD

**Issue by rafde** [foretagsplatsen/numbro#117]
I was looking at the documentation and maybe I wasn't looking hard enough but is there a way to get the value of `number`s like `1000.00` or `10.00` to return as `string`s `1.000,00` or `10,00` through `numbro`?

**Comment by BenjaminVanRyseghem** [comment]
Something like [this](http://numbrojs.com/try-me.html?lang=en-US&value=1000.00&format=%2C0.00)?

**Comment by rafde** [comment]
Unfortunately no. I am looking for the "."(period) to be used instead of ","(comma) and comma to be used in place of period.

Another example

10000000.76 =>10.000.000,76

**Comment by BenjaminVanRyseghem** [comment]
Then you have to define your own culture (which of course can be based on an existing one).

By changing the line [her](https://github.com/foretagsplatsen/numbro/blob/develop/languages/en-GB.js#L14) you should be able to achieve what you want :smile:

**Comment by rafde** [comment]
Interesting.
I suppose I can also submit a PR for `setDelimiters` that allows you to change it. Otherwise I am going to have to create an `angry-face` culture.

**Comment by BenjaminVanRyseghem** [comment]
I guess that could be a thing :wink:

**Comment by rafde** [comment]
Closing to address issue as a PR then. Thanks
