### ISSUE TITLE
Undocumented `roundingFunction`

### ISSUE THREAD

**Issue by pimskie** [foretagsplatsen/numbro#122]
If I'm right there's a undocumented feature, the `roundingFunction` argument for the methods `format`, `formatCurrency`, `formatPercentage` and `formatNumber`:

For example, on line #147:
```javascript
output =  formatCurrency(n, format, roundingFunction);
```

`roundingFunction` defaults to 'Math.min` so it seems:
```javascript
return formatNumbro(this,
    inputString ? inputString : defaultFormat,
     !== undefined) ? roundingFunction : Math.round
);
```
But can be overridden like:
```javascript
numbro(value).formatCurrency('0.000', Math.ceil);
```

**Comment by BenjaminVanRyseghem** [comment]
Indeed :smile:


The doc can be improved in many ways :smile:

**Comment by anuragagarwal561994** [comment]
Should this come under formatting or manipulation?

**Comment by BenjaminVanRyseghem** [comment]
formatting maybe?

**Comment by anuragagarwal561994** [comment]
Yes I already made a pull request for the same
