### ISSUE TITLE
grouping separator

### ISSUE THREAD

**Issue by titimoby** [foretagsplatsen/numbro#138]
As I previously formatted numbers using java, I was used to be able to group numbers.
For example, if I use:
`str = numbro(15000000.2).format('####,####.[##]');`
I'm waiting for this output:
`1500,0000.2`
but numbro gives me:
`15,000,000.2`

Is there a way to accomplish that with numbro?

**Comment by BenjaminVanRyseghem** [comment]
I do not think so :smile:

And I am not sure that's the way to go for numbro.
The idea is to have number formatted based on a culture, without the dev having to care about where to put separators etc.

**Comment by titimoby** [comment]
It's not a matter of the dev deciding where to put separator.
This grouping pattern is widely used among some of our customers and it was perfectly handled through Java.

The same apply to bi-format for positive/negative values.
It is useful to be able to declare a pattern like '###.00;(###.##)' 

Javascript format libraries based on pattern format are not so common, I wonder why.

**Comment by BenjaminVanRyseghem** [comment]
> Javascript format libraries based on pattern format are not so common, I wonder why.

I don't know :smile:

About pattern, the way numbro is implemented today (and I really don't like it) can't support such a feature.

Basically the main loop does regex in the format argument to find some options flag

**Comment by titimoby** [comment]
I checked the existing code and I understand what you mean by "(and I really don't like it)" ;)
That looks like a deep refactor is needed if you want to extend the capacities of Numbro.
I imagine that formatting number that represents something else (like a phone number for example (###)-##-####-#### whatever) will need such changes if it's a target at some point in this project life.
By the way, thanks for all the already accomplished work

**Comment by BenjaminVanRyseghem** [comment]
> That looks like a deep refactor is needed

![YES](http://www.sharegif.com/wp-content/uploads/2013/10/yes-gif-9.gif)

**Comment by titimoby** [comment]
I don't know how you like to handle issues for Numbre, but I got your point and I'm ok if this issue closes

**Comment by BenjaminVanRyseghem** [comment]
then I will close it for now, and we can discuss it again after the refactoring phase :smile:
