### ISSUE TITLE
numbro returns NaN on very small numbers

### ISSUE THREAD

**Issue by MarkHerhold** [foretagsplatsen/numbro#145]
```
numbro(-0.00000000000001).format('$0,0')
// returns "$NaN"
```

It is possible that I can PR a fix for this, but if someone knows what may be going on I would love to know.

**Comment by BenjaminVanRyseghem** [comment]
no clue sorry

**Comment by MarkHerhold** [comment]
@BenjaminVanRyseghem I've got a fix for this but it's on a branch that has my other PR included (#142). I'd like to merge that in then make a PR for this issue.

**Comment by BenjaminVanRyseghem** [comment]
great thanks :smile:

**Comment by MarkHerhold** [comment]
For the record:
I found more issues with small numbers and numbro while fixing the currency formatting issue. My PR will test for and address all of these:

From above:
```
numbro(-0.00000000000001).format('$0,0')
// returns "$NaN"
```
Error:
```
numbro(-1e-23).format("0.00000000000000000000000");
// RangeError: toFixed() digits argument must be between 0 and 20
```
Error:
```
numbro(-1e-23).format("0.00")
// TypeError: Cannot read property 'length' of undefined
```
