### ISSUE TITLE
Loading languages with requirejs

### ISSUE THREAD

**Issue by rudym87** [foretagsplatsen/numbro#148]
How can I load a language file in an AMD environment?
Currently trying to load languages.js or any single language file gives a `No define call for...` error.

**Comment by BenjaminVanRyseghem** [comment]
did you tried with the languages files in `dist/languages/`.

I think those one have an AMD wrapper

**Comment by rudym87** [comment]
Already tried, same error.

**Comment by BenjaminVanRyseghem** [comment]
> On 4 Apr, 2016, at 17:32, rudym87 <notifications@github.com> wrote:
> 
> Already tried, same error.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub <https://github.com/foretagsplatsen/numbro/issues/148#issuecomment-205352767>

then I need to investigate :smile:

which version do you use? have you tried several versions?

Thanks

**Comment by mmollick** [comment]
It doesn't look like there's any existing AMD support, just CommonJS and basic script tag support.
It probably wouldn't be too difficult to add in AMD support. Though I haven't used requirejs in quite a while so I can't recall what all is needed, I think it's `window.define`.

**Comment by BenjaminVanRyseghem** [comment]
we use numbro in production in an AMD environment (not the latest numbro though).

Support is [here](https://github.com/foretagsplatsen/numbro/blob/develop/dist/numbro.js#L1197)

**Comment by rudym87** [comment]
I did some tests, and loading languages fails when enabling in requirejs config `enforceDefine`, which is mainly used to [resolve some quirks of old IE versions](http://requirejs.org/docs/api.html#config-enforceDefine). 

Requirejs documentation doesn't state clearly if it applies to newer IE version too, so I don't really consider it a bug in numbro, i think i can safely disable `enforceDefine` in my case.

Anyway, for completeness' sake, here's a [jsfiddle](https://jsfiddle.net/zv6qjnzv/) to repoduce it.

**Comment by BenjaminVanRyseghem** [comment]
Here is a [working fiddle](https://jsfiddle.net/zv6qjnzv/2/). Let's hope you find it useful :smile:

**Comment by rudym87** [comment]
Numbro languages work fine even without shim, assuming they're required in the proper order.
Enabling `enforceDefine` still breaks your fiddle though.:smile:

**Comment by BenjaminVanRyseghem** [comment]
That's a bit cheating, but you can always do [that](https://jsfiddle.net/zv6qjnzv/3/)

**Comment by BenjaminVanRyseghem** [comment]
can we close this?

**Comment by rudym87** [comment]
Yes, the "cheat" is fine, i'm closing this.

**Comment by BenjaminVanRyseghem** [comment]
@rudym87 if you need it lees cheaty, we could introduce a map of imported lnaguages, so that you could have:

```
},
  shim: {
		'numbro-french': {
    	deps: ['numbro'],
      exports: "numbro.importedLanguages['fr-FR']"
    }
  }
```

or similar

**Comment by rudym87** [comment]
That can be an interesting solution, it can be used for other checks unrelated to requirejs.

**Comment by BenjaminVanRyseghem** [comment]
could you create another issue for it? :smile:

**Comment by rudym87** [comment]
Done!

**Comment by BenjaminVanRyseghem** [comment]
:+1:
