### ISSUE TITLE
unformat("not a number") returns 0

### ISSUE THREAD

**Issue by wereHamster** [foretagsplatsen/numbro#154]
I can't distinguish between `unformat` not being able to parse the string and the string indeed containing the number zero. `parseFloat` for example returns `NaN` in the failure case.

If you're against changing the semantics of `unformat` then I suggest a separate function, for example `unformatStrict`, which makes this distinction.

**Comment by BenjaminVanRyseghem** [comment]
looks like a bug to me. I think we should have the same semantic that `parseInt` :smile:

**Comment by wereHamster** [comment]
I would much rather have the same semantic like `Number()` except an empty string should be converted into `NaN` and not `0`.

**Comment by wereHamster** [comment]
I'll be away next week, so you'll have enough time to think about this. I'm open to changing the semantics of the existing function or creating a new function like in my pull request. Decide which way you'd like to go and I'll amend the code when I get back :)

**Comment by BenjaminVanRyseghem** [comment]
if you want the behavior of `Number()` except for empty sting, then what's the difference with `parseInt` ?

**Comment by wereHamster** [comment]
This is the difference:

```
> parseInt('1a')
1
> Number('1a')
NaN
> 
```

**Comment by BenjaminVanRyseghem** [comment]
indeed :smile:

**Comment by wereHamster** [comment]
So.. I'm back from my vacation. What do you prefer, changing the semantics of the existing `unformat` function or introducing a new function?

**Comment by BenjaminVanRyseghem** [comment]
welcome back :smile:

I think we can change the semantic.

A major version was on the pipe anyway, so it feels ok to do it now :smile:

**Comment by wereHamster** [comment]
This was fixed by #163.
