### ISSUE TITLE
Include TypeScript declaration file in the repository

### ISSUE THREAD

**Issue by wereHamster** [foretagsplatsen/numbro#156]
This would be a small change to the package.json file + a small numbro.d.ts file in the root of the repository. That way, users of this library won't have to download the declaration file from an external source and it would increase the chance that the two are always kept in sync, and when they import the library inside of a TypeScript project it would just work.

**Comment by BenjaminVanRyseghem** [comment]
if you know how to do it, it will be welcome :smile:

**Comment by wereHamster** [comment]
Yes, I know how. I did it for other npm packages in the past. As I said in the other issue, I'll be away for a week, but if nobody does it by then I'll send a pull request.
