### ISSUE TITLE
greater units for time than hours

### ISSUE THREAD

**Issue by samuraiii** [foretagsplatsen/numbro#160]
Hello it would be nice to have possibilty to format time up to years.
(quick and dirty hact to do this in numeral.js https://github.com/samuraiii/Numeral-js/commit/64d7f9378648980ffa0a91758eee36f4093478ab)

**Comment by BenjaminVanRyseghem** [comment]
your diff is impossible to read as your e indented everything.

Moreover, `numbro` is not meant to handle time as [momentjs](http://momentjs.com) does that very well

**Comment by wereHamster** [comment]
Diff with whitespace ignored: https://github.com/samuraiii/Numeral-js/commit/64d7f9378648980ffa0a91758eee36f4093478ab?w=1

**Comment by BenjaminVanRyseghem** [comment]
@samuraiii : could you add tests please?

**Comment by samuraiii** [comment]
tests?
I would like to but do not have idea what kind of tests

**Comment by BenjaminVanRyseghem** [comment]
there are tests where you put data, format, and expected output.

**Comment by andrewla** [comment]
This seems dangerous -- even the existing code looks a little dangerous!  The length of a year or a month is dependent on the current time to a significant degree.  Using months as 30 days and years as 365 days is a coarse approximation that should be used with caution, and is better suited to a library (like moment.js) that is dedicated to handling these cases.

**Comment by BenjaminVanRyseghem** [comment]
@andrewla  I totally agree with you.

I think I will remove this code sooner or later, as moment is made to handle that.

As I previously said,
> numbro is not meant to handle time as momentjs does that very well

:smile:
