### ISSUE TITLE
Bug with 1000s and decimal seprator

### ISSUE THREAD

**Issue by mpetkov** [foretagsplatsen/numbro#168]
Found the following bug when I was formatting some numbers:

Original Value: 8582065567.565
Format: '0,0.00000000'

Expected Value: 8,582,065,567.56500000
Actual Result: 8,582,065,567.56499958

**Comment by BenjaminVanRyseghem** [comment]
yep, JS sucks with decimals 😢

**Comment by mpetkov** [comment]
Any update on this? It has been a while :)
My suggestion to fix it just to treat the number as a string instead of a number.  Meaning just split by decimal and convert the decimal value to string and add 0s if necessary.

**Comment by NelsonReis** [comment]
That's very similar to #199

**Comment by BenjaminVanRyseghem** [comment]
they look really close indead :smile:

@mpetkov can you confirm they are the same, and maybe close this one as #199 is more detailed?

**Comment by mpetkov** [comment]
Yep, as long as you guys promise to fix it soon :smile:

**Comment by BenjaminVanRyseghem** [comment]
trust me I do my best, but time flies :smile:
