### ISSUE TITLE
Ignore abbreviations when importing existing or custom culture

### ISSUE THREAD

**Issue by cAstraea** [foretagsplatsen/numbro#179]
Is there a way to ignore the abbreviations when using 
 numbro.culture('fr-FR');
numbro(livre_prix).formatCurrency()

**Comment by BenjaminVanRyseghem** [comment]
what do you mean by "ignoring the abbreviation"?

**Comment by cAstraea** [comment]
oh my bad sorry should have looked better at the docs the abbreviations came from the a
Used a different default format without the a now and it's ok. 
Thanks for the help

**Comment by BenjaminVanRyseghem** [comment]
no problem :smile:
