### ISSUE TITLE
Redo the website

### ISSUE THREAD

**Issue by BenjaminVanRyseghem** [foretagsplatsen/numbro#18]
I would like to have a [bootstrap](www.getboostrap.com) like page with a navbar on top (one for formatting, one for currency, etc) and some categories in each page

What do you guys think?

**Comment by srph** [comment]
How about Jekyll?

**Comment by BenjaminVanRyseghem** [comment]
I think Jekyll is good when you have often new content (and by default, Jekyll is used for gh-pages).

I was thinking about doing the website the ol' classic way, but maybe using Jekyll syntax for a "News" section

**Comment by BenjaminVanRyseghem** [comment]
I have a first draft in a new [branch](https://github.com/foretagsplatsen/numbro/tree/feature/New_webpage).

It's done with Jekyll, so if you wanna try, you first need to install Jekyll: `$ gem install jekyll`, the serve the page with `$ jekyll serve`

**Comment by BenjaminVanRyseghem** [comment]
The website is done :smile: 

Just waiting for a logo as explained here: #19

**Comment by robertbaker** [comment]
Launch the site w/o the logo.

**Comment by BenjaminVanRyseghem** [comment]
I'd wait for a logo.

I think it's more catchy ;)

**Comment by BenjaminVanRyseghem** [comment]
Done and online :smile:

**Comment by NikoDelarich** [comment]
All the links on top return "404 - File not found" for me.
I believe the links should point to e.g. "getting-started.html" instead of "/getting-started.html"...

**Comment by BenjaminVanRyseghem** [comment]
Which browser are you using?

It works for me on Chromium 41.0.2272.76 (64-bit)
