### ISSUE TITLE
We need a logo for numbro

### ISSUE THREAD

**Issue by NicolasPetton** [foretagsplatsen/numbro#19]
Hi guys,

We definitely need a logo :)
Any idea?

**Comment by BenjaminVanRyseghem** [comment]
I was thinking of a number doing a bro fist, but I failed in finding a bro fist svg file to try :smile:

**Comment by uniphil** [comment]
not really into the "bro" thing, personally. maybe we can get a mascot instead of a logo?

**Comment by BenjaminVanRyseghem** [comment]
why not :smile: 

Feel free to propose ideas :wink:

**Comment by BenjaminVanRyseghem** [comment]
I personally recommend a raccoon as they are fucking cute :smiley_cat:

**Comment by BenjaminVanRyseghem** [comment]
![screen shot 2015-04-23 at 9 28 48 pm](https://cloud.githubusercontent.com/assets/407891/7305648/cc2d6dd2-e9ff-11e4-88dc-ffc9eea822a2.png)

Something like this would be awesome :stuck_out_tongue_winking_eye:

**Comment by uniphil** [comment]
lol amazing. I'm down for that.

**Comment by NicolasPetton** [comment]
:+1:

**Comment by BenjaminVanRyseghem** [comment]
You can now find **Ranko the Raccoon** [here](https://github.com/foretagsplatsen/numbro/tree/develop/resources)
:smile:

**Comment by uniphil** [comment]
:tada:
