### ISSUE TITLE
Fixed precision for average

### ISSUE THREAD

**Issue by tehandyb** [foretagsplatsen/numbro#190]
I saw the average formatter lets you specify precision when the number gets rounded up, but I have commonly had the use case where I want a fixed precision of 3 digits no matter what the number was and whether it was rounded or not. 

So numbro(12345).format('3a') would give 12.3k instead of currently 12k

**Comment by chrisnicola** [comment]
This seems to be a bug, for every value less than 4 it does exactly the same thing. You can even see this behaviour happening in the docs right now.

**Comment by chrisnicola** [comment]
Seems the way to do this is `'000a'` rather than `'3a'`. I must say I find the inconsistency here confusing though.

**Comment by chrisnicola** [comment]
So I was wrong, doing `000` will add leading zeros. I've submitted a patch for this. For reasons I don't understand it simply skips precision formatting for values less than 4.
