### ISSUE TITLE
Comma for radix point, decimal for thousands delimeter?

### ISSUE THREAD

**Issue by johnryan1** [foretagsplatsen/numbro#191]
I'm trying out this plugin.  Initially, just want simple functionality.
For North American number formatting, I want a comma for a thousands separator and the period as the decimal place...with two decimal place.  The following works fine...
$(this).val(numbro($(this).val()).format("(0,0.00)"));
ex: 1234 = 1,234.00 (good)
Now I want the thousands separator to be a period and the radix point to be a comma but with the following format where the comma and decimal are swapped, seems to get ignored.
$(this).val(numbro($(this).val()).format("(0.0,00)"));
ex: 1234 should be 1.234,00 but instead it's 1,234.0000

I'm not finding this as an issue anywhere yet so I am thinking that I'm just doing it wrong...but the format string seems pretty straightforward.

**Comment by NelsonReis** [comment]
You should set the format through the culture, like this:
```
var number = 1234;
console.log(numbro(number).format("(0,0.00)"));
numbro.culture('custom', {
    delimiters: {
        thousands: '.',
        decimal: ','
    }
});
numbro.culture('custom');
console.log(numbro(number).format("(0,0.00)"));
```
First you set the culture definition, then you apply it to the numbro instance.
Notice that the format string is the same, the change is only on the delimiters of the culture.

**Comment by johnryan1** [comment]
Nelson, thanks so much.   This works!
