### ISSUE TITLE
Format long decimal without rounding

### ISSUE THREAD

**Issue by NelsonReis** [foretagsplatsen/numbro#199]
I'm trying to format a number with a lot of decimal places but would not want it to be rounded.
I want to show all decimal places as the original value, for instance:

```
-40.1234567         => "-40.1234567"
-40.123456789       => "-40.123456789"
-40.123456789012345 => "-40.123456789012345"
```

To accomplish this, I would use a format like: `format('#.[####################]')` .
The issue is that if the format contains more than 14 "#" on the decimal places side, it will start giving results as (for the values above):

```
"-40.12345669999999842048"
"-40.12345678900000223166"
"-40.12345678901234435898"
```

I've managed to work around it placing a format with an `*` (which I didn't find on the docs), as: `format('#.*')` .
This way would give me the following results (still not perfect, but workable):

```
-40.1234567         => "-40.1234567"
-40.123456789       => "-40.123456789"
-40.123456789012345 => "-40.123456789012344" (notice the last number is "4", should be "5", still it would work for me)
```

The problem with this format is that if the number doesn't have any decimal places, it would generate an error:

```
numbro(-40).format('#.*')
```

> numbro.js:643 Uncaught TypeError: Cannot read property 'length' of undefined

Is there any way to solve this? Thanks.

**Comment by BenjaminVanRyseghem** [comment]
`numbro(-40).format('#.*')` sounds like a bug...

for 

```
-40.123456789012345 => "-40.123456789012344" (notice the last number is "4", should be "5", still it would work for me)
```


the problem is JS itself which sucks pretty hard when it comes to floats...

**Comment by NelsonReis** [comment]
Anyways, what's the right syntax for the "*" symbol on the format?
As I could not find it on the docs, maybe someone else could also find it useful.

For the issue with JavaScript and floats, I'm aware of that, and that's why I've said it would still work for me, got to acknowledge that the world isn't perfect :smile: 

Would really appreciate if someone could get around the bug on `numbro(-40).format('#.*')` .

**Comment by BenjaminVanRyseghem** [comment]
> what's the right syntax for the "*" symbol on the format?

no clue :smile:

>  if someone could get around the bug on numbro(-40).format('#.*') .

it sounds like easy to fix, unfortunately, I am quite busy those days 😕
