### ISSUE TITLE
apostrophe for thousands

### ISSUE THREAD

**Issue by Remo** [foretagsplatsen/numbro#204]
I already posted this problem here https://github.com/adamwdraper/Numeral-js/issues/338, but it seems like numeraljs is pretty much dead, maybe I've got more luck over here.

---

Two small countries, Switzerland and Liechtenstein, are often using apostrophe for thousands. See https://en.wikipedia.org/wiki/Decimal_mark

I would have expected this to work:
```
numbro(1230).format("0'0.00") // = 1'230.00
```

Any pointers to get me in the right direction?

**Comment by BenjaminVanRyseghem** [comment]
Hello :smile:

2 solutions:

- the decimal mark correspond to a culture (like `de-CH`) and then we need to update our code [here](https://github.com/foretagsplatsen/numbro/blob/develop/languages/de-CH.js)
- it's more of an colloquial usage, then you need to define your own custom culture, see [documentation](http://numbrojs.com/languages.html#define-language)

I hope it helps

**Comment by Remo** [comment]
Thanks, much appreciated! Seems like this fork is much better maintained :smile: 
If it was up to me I would definitely change the culture, but I'm not 100% sure that everyone will agree. I'll ask around, maybe someone knows more about this.

**Comment by BenjaminVanRyseghem** [comment]
> Thanks, much appreciated! Seems like this fork is much better maintained 😄

we try our best :smile:
> If it was up to me I would definitely change the culture, but I'm not 100% sure that everyone will agree. I'll ask around, maybe someone knows more about this
> 
Nice! Keep us updated

**Comment by Remo** [comment]
I assume Microsoft did research questions like that.
```csharp
int i = 1320;
Thread.CurrentThread.CurrentCulture = new CultureInfo("de-CH", false);
i.ToString("c");
```

This produces `CHF 1'320.00`

**Comment by Remo** [comment]
Whatever information I find and get seems to be in line with my thinking and in my opinion the fact that .NET does it the way I think it should be, is a strong argument. Pull request created.

**Comment by pimskie** [comment]
Exactly what I was looking for. Thanks for fixing. Could this change also be published on NPM?

**Comment by BenjaminVanRyseghem** [comment]
I think it’s automatically publish on npm when we do a release :smile:

**Comment by pimskie** [comment]
lol, forget my noob comment.
