### ISSUE TITLE
Setting numbro culture

### ISSUE THREAD

**Issue by johnnytn** [foretagsplatsen/numbro#209]
So I've been trying to change `numbro`'s culture for the whole day... 

I've tried the simple way, but got and error: **Unknown culture : ' + code**
`numbro.culture('fr-FR');`

tried like this:
`const br = require('numbro/languages/pt-BR')
numbro.culture('pt-BR', br)`

but nothing changes and the default culture is applied.. Can anyone give me a hand?

**Comment by BenjaminVanRyseghem** [comment]
are you sure the cultures you are trying to use are loaded?

If you go [here](http://numbrojs.com/try-me.html) and open the dev tools,
you can do: 

```js
numbro.culture('pt-BR');
numbro('45').formatCurrency(); // "R$45 "
```

**Comment by ionian-wind** [comment]
had same issue
working code:
```javascript
const numbro = require('numbro');
numbro.culture('ru-RU', require('numbro/languages/ru-RU'));
numbro.culture('ru-RU');
numbro('45').formatCurrency(); // "45 руб."
```
