### ISSUE TITLE
Unhelpful Error Message Regarding Curley Braces

### ISSUE THREAD

**Issue by reustle** [foretagsplatsen/numbro#213]
For example, if you use the following string as a format string `$` without any numbers or parens, you get the following error message:

`numbro.min.js:76 Uncaught Error: Format should also contain a "{"`

I didn't realize I forgot to use `$0,0` but the error message seemed odd. Maybe it should instead say something about missing the value placeholder?

**Comment by BenjaminVanRyseghem** [comment]
sounds like a good improvement indeed :smile:
