### ISSUE TITLE
Numbro overrides € with $

### ISSUE THREAD

**Issue by elcortez** [foretagsplatsen/numbro#224]
Hello and thanks for developing this
I currently have an issue with the currency sign; i have € 50% of the time, and $ otherwise.

I tried putting 'numbro.language('fr-FR');' on top of the js file (i'm on a react app) but I have not been successful so far.

numbro(123).formatCurrency('0[.]00 €')
-> Gives me either '123€' or '$123'

numbro(123).formatCurrency('0[.]00')
-> Same thing

I tried running it on https://runkit.com/npm/numbro but I get an error message 'numbro is not defined'

**Comment by BenjaminVanRyseghem** [comment]
never heard of that issue before 😕

**Comment by elcortez** [comment]
I was actually wondering if it was me who's doing it wrong, since I'm new to JS/React, maybe I'm calling the functions the wrong way?
