### ISSUE TITLE
Add Numbro to cdnjs

### ISSUE THREAD

**Issue by BenjaminVanRyseghem** [foretagsplatsen/numbro#23]
See [doc](https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library)

**Comment by BenjaminVanRyseghem** [comment]
[PR open](https://github.com/cdnjs/cdnjs/pull/4579), now I am waiting for them to merge it :smile: 

Maybe a :+1: can help :smile:

**Comment by Graham42** [comment]
I think the only thing that's still needed here is to add steps to our [Publishing](https://github.com/foretagsplatsen/numbro/wiki/Publishing) wiki page on how to keep this up to date.

**Comment by BenjaminVanRyseghem** [comment]
When I search for numbro on cdnjs, I still can't find it.

**Comment by Graham42** [comment]
After reading, looks like things should autoupdated from their side. I've asked about it not showing up in that PR.

**Comment by Graham42** [comment]
They seemed to have pushed some button to make it work, I'm seeing it show up now. 

However, shouldn't the main file be `min/numbro.min.js` instead of `languages.js`? https://github.com/BenjaminVanRyseghem/cdnjs/blob/72f34972a1238d1a78d018d4012782b1814e85c1/ajax/libs/numbro/package.json#L59

**Comment by BenjaminVanRyseghem** [comment]
It should definitely be.

I used the auto-conf command line they recommend, but it looks a bit unprecise :disappointed:

**Comment by BenjaminVanRyseghem** [comment]
PR open

**Comment by BenjaminVanRyseghem** [comment]
done, and webpage updated
