### ISSUE TITLE
Español culture code is wrong

### ISSUE THREAD

**Issue by BenjaminVanRyseghem** [foretagsplatsen/numbro#24]
See [here](https://github.com/foretagsplatsen/numbro/blob/develop/languages/es-ES.js#L47)

**Comment by maheshsenni** [comment]
Looks like a simple fix. I am surprised that this is not captured in the tests. One difficulty I see is that the culture codes are not maintained as properties of language objects which is not helping while testing.

**Comment by BenjaminVanRyseghem** [comment]
I think we should add a test that check that the language key follows "xxx-XXX" format (2 parts separated by a `-` the first one lowercase, the second one uppercase) :smile:

**Comment by maheshsenni** [comment]
Agreed. Even with this test is place, nothing will stop us from adding some random string as language key as there is no validation on the culture code supplied.

The format can be enforced (regex maybe - `\^[a-z]{2}-[A-Z]{2}$`)while loading the laguages here [`loadLanguage`](https://github.com/foretagsplatsen/numbro/blob/develop/numbro.js#L746). What do you suggest?

I am also seeing some culture codes like `Cy-sr-SP` in the [MSDN reference](https://msdn.microsoft.com/en-us/library/ee825488.aspx).

**Comment by BenjaminVanRyseghem** [comment]
we should try to ensure it's a valid msdn format, but it can also be some iso code :/

**Comment by maheshsenni** [comment]
Added a validation for codes in this commit 53ad85e1debc69ba43fc1583876580e851515ba6. It checks for the pattern xx(x)-XX(X). Could be improved though, may be with a pattern like [this](http://stackoverflow.com/a/3962578/1702775).

Looks like the tests have to be fixed as well. Lot of test cases are failing as the codes used are not in the proper format - like [here](https://github.com/foretagsplatsen/numbro/blob/develop/tests/languages/chs.js#L6) and [here](https://github.com/foretagsplatsen/numbro/blob/develop/tests/languages/be-nl.js#L6).

Would you prefer a separate issue opened for this?

**Comment by BenjaminVanRyseghem** [comment]
There is an issue already for the test files #31

**Comment by BenjaminVanRyseghem** [comment]
Beside that, I would rather add this check as a numbro test, and not in the `loadLanguage` function, as I do not want to constraint users when they want to define their own languages

**Comment by maheshsenni** [comment]
Makes sense. Submitting a PR for Español code correction. Will work on the tests in #31.

**Comment by BenjaminVanRyseghem** [comment]
Now that the #31 is closed, do you have a PR with your regex so we can discuss it? :smile:

**Comment by maheshsenni** [comment]
Sure. Will work on it. Now that we have `langLocaleCode` as part of languages, adding tests should be straight forward.

**Comment by BenjaminVanRyseghem** [comment]
good :+1:

**Comment by maheshsenni** [comment]
Created new test for the culture codes in this commit - ddcc3eab66cda17c657011d56a0338ebdbf535b6

I have added a new module [require-dir](https://www.npmjs.com/package/require-dir) which loads up all the language modules in `/languages` directory for testing.

This is helpful because, we do not need to maintain a list of language modules available - all the modules in `/language` are assumed to be language modules and are tested.

If you think requiring `require-dir` in overkill, I can put together a piece of code which can do the same.

**Comment by BenjaminVanRyseghem** [comment]
The code look good :smile: 

I do not mind requiring `require-dir` as it's stripped down when uglified :wink:

**Comment by maheshsenni** [comment]
Submitted PR #44

**Comment by BenjaminVanRyseghem** [comment]
PR merged :+1: 

Thank you :smile:

**Comment by eliseumds** [comment]
May this issue be closed?

**Comment by BenjaminVanRyseghem** [comment]
Yes :+1:
