### ISSUE TITLE
Please update npm package with new d.ts file

### ISSUE THREAD

**Issue by bherila** [foretagsplatsen/numbro#284]
Since merging #232 it would be very helpful to be able to install that updated file from npm

When will we be able to see the updated file in the npm package? Doesn't look like it got included in the last release for some reason.

Thanks,
Ben

**Comment by BenjaminVanRyseghem** [comment]
euh ok :/ I will investigate :smile:

Not sure to have the time this week, I will try to do it next monday if that's ok. Do not hesitate to ping me if I forget

**Comment by bherila** [comment]
Thanks, I have copied the file manually for the time being, but it keeps getting overwritten when the build script reinstalls all the packages.

**Comment by sousarka** [comment]
@BenjaminVanRyseghem ping!

**Comment by BenjaminVanRyseghem** [comment]
on it :smile:

**Comment by BenjaminVanRyseghem** [comment]
This should be in numbro 1.11.0 :smile:

**Comment by BenjaminVanRyseghem** [comment]
can you confirm?

**Comment by sousarka** [comment]
the new numbro type definition (numbro.d.ts) is perfectly working.. Thank you so much for this awesome library.

**Comment by bherila** [comment]
Awesome, thank you so much!! 👍
