### ISSUE TITLE
Consider adding more contributors with write access

### ISSUE THREAD

**Issue by herodrigues** [foretagsplatsen/numbro#299]
This library is really awesome and could have a ton of improvements. I'm currently using it in two projects of mine and I know many developers that are using it too.

I see many open (with all checks passed) PRs and they're not merged that often. Probably due to lack of time from the project creators.

@BenjaminVanRyseghem have you considered adding more people to this project?

**Comment by BenjaminVanRyseghem** [comment]
@herodrigues I left my position in this company, so I suddently got more free time to work on numbro :smile:

I am back from vacations, so I will try to push it very hard now.

Now to answer your question, I am willing to, but no one really came to me to ask to be maintainer, so it just didn't happened :smile:

**Comment by herodrigues** [comment]
Great! I'll try to contribute as much as I can with PRs

**Comment by ArmorDarks** [comment]
Cool!
