### ISSUE TITLE
Inconsistent whitespace

### ISSUE THREAD

**Issue by Graham42** [foretagsplatsen/numbro#30]
I've noticed that indentation throughout the project mixes spaces and tabs which is really bad. The majority is 4-space indent so should we switch everything to that? I care less about what the indenation is and more that it should be consistent. It's important for having readable and meaningful diffs.

Once this is decided I'll make a pull request with the required changes and then add a grunt test to make sure new pull requests have whitespace consistent with the rest of the project.

**Comment by BenjaminVanRyseghem** [comment]
It's usually 4 tabs, and I am in favor of that :)

Now I have to check my webstorm settings to be sure I didn't do shit :P
