### ISSUE TITLE
Numbro includes all locales in webpack bundle

### ISSUE THREAD

**Issue by ClementParis016** [foretagsplatsen/numbro#304]
As per [this line in index.js](https://github.com/foretagsplatsen/numbro/blob/develop/numbro.js#L1021):
```js
var cultures = require('./languages');
```
And regarding [the content of languages/index.js](https://github.com/foretagsplatsen/numbro/blob/develop/languages/index.js), which requires itself absolutely every single language of the languages/ folder, it appears that once bundled (by webpack or any other module bundler), all locales are compiled to the output.

This is seriously a bad thing to do, because the source code of numbro is smaller (43.1 kB) than all the locales combined (75.99 kB) so it makes the whole thing heavier than it should be.

You can find instructions and detailed information about how to work around this problem on this webpack issue about Moment.js: https://github.com/webpack/webpack/issues/3128

**Comment by BenjaminVanRyseghem** [comment]
I am on it :smile:

Thanks for your feedback

**Comment by ClementParis016** [comment]
Great! Is this planned for a future version?

**Comment by BenjaminVanRyseghem** [comment]
it should be in 2.0.0

**Comment by ClementParis016** [comment]
Alright, I took a quick look through the 2.0 branch, it looks like you're on track ;)
