### ISSUE TITLE
Top links on website do not work

### ISSUE THREAD

**Issue by NikoDelarich** [foretagsplatsen/numbro#37]
When I visit the numbro website at https://foretagsplatsen.github.io/numbro/, none of the links on top (except "numbro") work correctly.
For example, the "Getting Started"-link leads to "https://foretagsplatsen.github.io/getting-started.html" instead of "https://foretagsplatsen.github.io/numbro/getting-started.html".

I can reproduce this behaviour in all major browsers (IE11, FF37, Chrome42) on my Windows 7 x64 PC.

![2015-04-27 09_38_33-numbro js](https://cloud.githubusercontent.com/assets/2089413/7343386/539a8264-ecc1-11e4-94d3-ed28e594f80f.png)

**Comment by BenjaminVanRyseghem** [comment]
Indeed :+1: 

When I made the website, I was using [numbrojs.com](https://numbrojs.com).
So having urls on top level was not a problem :smile: 

I will fix this asap

**Comment by NikoDelarich** [comment]
I see :smile: 
Maybe you should also link to numbrojs.com from README.md - I had no idea the project had a "proper" domain until now :wink:

**Comment by BenjaminVanRyseghem** [comment]
it was there:

![screen shot 2015-04-27 at 10 34 22 am](https://cloud.githubusercontent.com/assets/407891/7344092/064ba9f4-ecc9-11e4-9564-ddf4504e68bb.png)

I will fix it anyway ;)
