### ISSUE TITLE
Documentation page

### ISSUE THREAD

**Issue by srph** [foretagsplatsen/numbro#4]
The documentation page doesn't seem to be available yet.

**Comment by BenjaminVanRyseghem** [comment]
Indeed :smile: 

I am waiting for my company to buy the domain name :smile: 

It should be done today

**Comment by srph** [comment]
Ah -- domain name?! Wow, that's a pretty generous move, thanks.

**Comment by BenjaminVanRyseghem** [comment]
:smile_cat: 
It's bought, I will give it a try today or tomorrow

**Comment by srph** [comment]
Thanks! Closing this now.
