### ISSUE TITLE
defaultFormatCurrency

### ISSUE THREAD

**Issue by robertbaker** [foretagsplatsen/numbro#46]
formatCurrency has no default setter.

I want formatCurrency() to default to `0,0[.]00` (with the currency symbol in the correct place)

**Comment by BenjaminVanRyseghem** [comment]
Sorry for the delay, I was pretty busy those days.

Actually this already exists (but not yet documented)

You can do: 

~~~javascript
numbro.defaultCurrencyFormat('0,0[.]00');
numbro(123).formatCurrency();
~~~

And it keeps the language specifics defaults (pre/postfix etc)
