### ISSUE TITLE
Improve docs, explain [.]

### ISSUE THREAD

**Issue by robertbaker** [foretagsplatsen/numbro#49]
I'm not sure what `[.]` does vs `.`

```
numbro.setDefaultCurrencyFormat('0,0.00');
vs
numbro.setDefaultCurrencyFormat('0,0[.]00');

```
Does `[.]` make the decimal optional? For example 8.00 would be $8 not $8.00. but 8.1 would be $8.10

**Comment by BenjaminVanRyseghem** [comment]
Exactly

~~~javascript
numbro(12).format('0.00') // 12.00
numbro(12).format('0[.]00') // 12

numbro(12.34).format('0.00') // 12.34
numbro(12).34.format('0[.]00') // 12.34
~~~

**Comment by homer2** [comment]
Is there a format to remove insignificant trailing zeros?

    numbro(12.34).format('0[.]0?') // 12.34
    numbro(12.30).format('0[.]0?') // 12.3

**Comment by BenjaminVanRyseghem** [comment]
Not that I am aware of :smile:

Could you report it in a separate entry?

Thanks

**Comment by BenjaminVanRyseghem** [comment]
I close this issue as the separate issue reported here looks similar to #68
