### ISSUE TITLE
npm package not found

### ISSUE THREAD

**Issue by mygithongxia** [foretagsplatsen/numbro#5]
![2015-04-08 6 07 22](https://cloud.githubusercontent.com/assets/9877311/7043181/39ffcc70-de1a-11e4-940a-421541771e19.png)

https://www.npmjs.com/package/numbro

**Comment by BenjaminVanRyseghem** [comment]
Fixed :)

I was just fighting with npm at the moment :)

Everything should be back on track now :smile: 

Thanks
