### ISSUE TITLE
Max significant numbers formating

### ISSUE THREAD

**Issue by Benoss** [foretagsplatsen/numbro#53]
Looking at the doc I can't find a way to fix the number of significant numbers. This is very useful when you are showing numbers in a fixed width container

For example if I want only 3 significant numbers:
* 12345678=> 12.3m
* 1234567=> 1.23m
* 123456 => 123k
* 12345 => 12.3k
* 1234 => 1.23k
* 123 => 123
* 12.3 => 12.3
* 1.23 => 1.23
* 0.123 => 0.12
* 0.0123 => 0.01

format string could be "3a" for this example

**Comment by BenjaminVanRyseghem** [comment]
You can use this format `00000 a` by example, to fix the significant number to 5

But surprisingly enough, it doesn't work for a number of 0 lesser than 4 :confused: 

I will investigate :smile:

**Comment by BenjaminVanRyseghem** [comment]
Fix proposed :smile:

I will also improve documentation in a separate issue #56

**Comment by BenjaminVanRyseghem** [comment]
In numbro 1.2.3

**Comment by Benoss** [comment]
Thanks for the fix but I still don't get it for a precision of  2 and 3
In the doc:
1234567891	'2a'	1b
1234567891	'3a'	1b

should 3a be 1.23b
and 2a be 1.2b ?

**Comment by BenjaminVanRyseghem** [comment]
Yep, I noticed this.

I will have to investigate this

**Comment by BenjaminVanRyseghem** [comment]
Let's open a new ticket :smile:
