### ISSUE TITLE
Use webstorm to replace numeral with numbro in gh-pages

### ISSUE THREAD

**Issue by robertbaker** [foretagsplatsen/numbro#6]
Open the folder in webstorm. right click replace in path
Preserve case - checked, recursive checked.

find: numeraljs, replace: numbro
then
find: numeral, replace: numbro

That should take care of all the renaming and preserve casing so Numeral would be Numbro

**Comment by BenjaminVanRyseghem** [comment]
I think there is no more references to `Numeral`, or am I wrong?

**Comment by robertbaker** [comment]
Yes the web site

**Comment by BenjaminVanRyseghem** [comment]
ahh ok :)

That's still work in progress :smile:

**Comment by BenjaminVanRyseghem** [comment]
http://numbrojs.com/ is up
