### ISSUE TITLE
using languages in node

### ISSUE THREAD

**Issue by stewart42** [foretagsplatsen/numbro#62]
Hi there,

I think I am missing something :/ 

in node, load an additional language
```js
var numbro = require('numbro');
numbro.language('en-ZA', require('../node_modules/numbro/dist/languages/en-ZA.min.js'));
numbro.language('en-ZA');
```

Would I need to do this for all the languages I would like available to the app?

**Comment by BenjaminVanRyseghem** [comment]
According to the current code, I would say yes.

But it sucks badly :smile: I will try to have a look to improve that (or if you want to propose a PR, feel free :stuck_out_tongue: )

**Comment by BenjaminVanRyseghem** [comment]
In numbro 1.4.0

**Comment by stewart42** [comment]
Thanks guys
