### ISSUE TITLE
multiply loses accuracy on minification

### ISSUE THREAD

**Issue by rafde** [foretagsplatsen/numbro#64]
This is a problem that was noticed at my work for numeraljs
https://github.com/foretagsplatsen/numbro/blob/develop/numbro.js#L930-L937
where
```
...
var corrFactor = correctionFactor(accum, curr);
return (accum * corrFactor) * (curr * corrFactor) /
    (corrFactor * corrFactor);
```
the minifier will remove all those parenthesis and mess up the order of operation.
A more cumbersome but accurate solution:
```
var corrFactor = correctionFactor(accum, curr),
      result = accum * corrFactor;
      result *= curr * corrFactor;
      result /= corrFactor * corrFactor
return result;
```
or however you see fit, so long as the order is maintain after minifying.
Test against
`numbro(46.6).multiply(0.575) === 26.795`

**Comment by BenjaminVanRyseghem** [comment]
I am not sure to understand everything :smile:

```
46.6 * 0.575
// 26.794999999999998
```

```
numbro(46.6).multiply(0.575).value()
\\ 26.794999999999995
```

and

```
numbro(46.6).multiply(0.575).value() - (46.6 * 0.575)
// -3.552713678800501e-15
```

So I do not really see the issue here.

Am I missing something?

(I have no idea with your fix as long as at least I understand why there is an issue :smile:)

**Comment by rafde** [comment]
This is the issue. When the file gets minified, it looks like this:
```
multiply   : function (a) {
        function b(a, b) {
          var c = l(a, b);
          return a * c * b * c / (
            c * c)
        }
```
so `a * c * b * c` is suppose to be kept as `(a * c) * (b * c)`, but the minifier doesn't know that.
The parenthesis are removed and the order of intentional operation is lost.

**Comment by BenjaminVanRyseghem** [comment]
The example I wrote was with minified code. And I still don't see the issue

On top of that, `(a * b) * (c * d)` is exactly the same as `a * b * c * d` (at least at a theoretical level)

If you could try to really point out what is wrong :smile:

**Comment by rafde** [comment]
I just realized that the example you provided
```
numbro(46.6).multiply(0.575).value()
// 26.794999999999995
```
is my point. Un-minified version returns `26.795`, minified version returns `26.794999999999995`.
The expected result is `26.795`

**Comment by BenjaminVanRyseghem** [comment]
ok :smile: now I get it :+1: 

Then we can definitely split off the code to ensure the minified version works as expected.

Do you want to propose a PR?

**Comment by rafde** [comment]
I would like to but I won't be able to get to making the PR till Thursday. Plus I need to figure out [where to include the test](https://github.com/foretagsplatsen/numbro/tree/develop/tests) for it .

**Comment by BenjaminVanRyseghem** [comment]
it's not in a hurry for me :smile:

About the test, I would skip it, as testing the minified code is not part of numbro :smile:

You should report the bug to the minifier issue tracker

**Comment by rafde** [comment]
> About the test, I would skip it, as testing the minified code is not part of numbro

Maybe it's a good time to start since accuracy is important and the minifying process might be affecting other parts of the code. Otherwise, it's no better than doing native math.

> You should report the bug to the minifier issue tracker

I might, but I am trying to imagine what a solution might be.

**Comment by BenjaminVanRyseghem** [comment]
Why not, I will try to give it a try then :smile:

A solution might be to keep the parenthesis all the time. It will expand the code by a couple of parenthesis, but knowing that js and floats are not that good friend, it could be worth it :smile:

**Comment by rafde** [comment]
Too late. I referenced the issue.

**Comment by rafde** [comment]
When do patches happen?

**Comment by BenjaminVanRyseghem** [comment]
I do not get your question

**Comment by rafde** [comment]
When will this fix get released?

**Comment by BenjaminVanRyseghem** [comment]
probably tomorrow if I can find 15 minutes :smile: 

I had another issue I wanted to work on first, but that can definitely be 2 separates updates :smile:

**Comment by rafde** [comment]
Thanks for the response.
Looking forward to replacing numeral with this lib.

**Comment by BenjaminVanRyseghem** [comment]
In numbro 1.3.3

**Comment by rafde** [comment]
:tada:
