### ISSUE TITLE
Release 1.3.1

### ISSUE THREAD

**Issue by Lodivol** [foretagsplatsen/numbro#65]
Hi,

I was interested to get the last release of numbro (1.3.1) in order to fix a bug encountered with browserify.  
Thus, I installed the last version from npm and unfortunately the bug was still present.
I checked the code of the package and it seems that the bug is still presents because  the code hasn't been updated (latest pull request from Avetisk is missing)

Files on npm are different from the version currently deployed on git master branch.
(I tried to install the package directly from git  and it works well) 

Could you check that  the version on npm is correct ?

Thx.

**Comment by BenjaminVanRyseghem** [comment]
indeed it looks wrong when I look at the git tag at least

I may have fucked up the release :smile:

I will do another one right now :smile:

**Comment by BenjaminVanRyseghem** [comment]
I just released 1.3.2.

I hope it worked fine this time :smile:

**Comment by Lodivol** [comment]
It works fine, thx ! :-)
