### ISSUE TITLE
Format decimal numbers

### ISSUE THREAD

**Issue by karellm** [foretagsplatsen/numbro#68]
I stumble uppon your repo while skimming the many numeral.js issues. I'm trying to do some very basic formatting: `123456.123456` to `123'456.123456`. Or in words:

1. Format the part before the period
2. Leave decimals untouched

`numeral.js` and `numbro` both seem to require you to know the number of decimals ahead or setting a big number (which will generate extra 0 at the end of the number).

Am I missing something? Thanks!

**Comment by BenjaminVanRyseghem** [comment]
for the first bullet, you can try [`,0`](http://numbrojs.com/try-me.html?lang=en-US&value=3124213.12341234&format=%2C0) as format

for the second bullet, I do not know if leaving the decimal untouched is supported (yet?)
I tried something like [`0.`](http://numbrojs.com/try-me.html?lang=en-US&value=3124213.12341234&format=0.) but it didn't work

I will have a deeper look tomorrow, and hopefully propose a fix for it

**Comment by karellm** [comment]
I forgot to mention I tried all I could think of: `0,0[.0000000000]`, `0,0[.]0000000000` or alike.

If I can make a suggestion, I would borrow regex syntax here: `0,0[.]0*` where `*` pretty much means any number of digits including none.
