### ISSUE TITLE
Trailing "B" when formatting ordinal numbers

### ISSUE THREAD

**Issue by jsoulet** [foretagsplatsen/numbro#69]
Hi,
I'm using your lib to format international ordinal numbers :

     numbro(myVar).format('ordinal')

Therefore, instead of getting "1st", I get a "1stB"
It's due to format format checker which use the d letter to check if a decimal formatting has been asked

I would recommand to set

    bytes = ''

when you know the user has asked for an ordinal formatting (line 462 - 479)

Meanwhile, i'm using it that way

    numbro(myVar).format('orinal')

Thanks

**Comment by BenjaminVanRyseghem** [comment]
I think you are missing the end of your explanation here :smile:

**Comment by jsoulet** [comment]
Sorry, I mis-pressed Enter

**Comment by BenjaminVanRyseghem** [comment]
Why do you use `ordinal` as format?

To have ordinal, the format should only contains a `o` (as you can see [here](http://numbrojs.com/try-me.html?lang=en-US&value=123&format=0o))

**Comment by jsoulet** [comment]
Thank you for your really fast help :)

**Comment by BenjaminVanRyseghem** [comment]
Can I close this issue? :smile:

**Comment by BenjaminVanRyseghem** [comment]
you're welcome :smile:
