### ISSUE TITLE
node 0.12 support

### ISSUE THREAD

**Issue by uniphil** [foretagsplatsen/numbro#7]
`npm test` and `grunt build` are currently failing under node v0.12. It would be nice if that runtime were supported.

**Comment by BenjaminVanRyseghem** [comment]
indeed, but I don't get why it fails

**Comment by BenjaminVanRyseghem** [comment]
can you please check that #9 fixes this issue?

**Comment by uniphil** [comment]
yep! found the same fix yesterday :) I PR'd (#11) a change to run travis in more versions to the branch in #9 too (with help from @graham42).
