### ISSUE TITLE
Incorrectly reporting hasModule = true

### ISSUE THREAD

**Issue by montogeek** [foretagsplatsen/numbro#71]
Hi!

I am using numbro in the browser, like this:
```javascript
var numbro = require('numbro');
```

But when compiling the source file I get this error on Chrome:
```
Uncaught TypeError: x.readdirSync is not a function
```

Basically the `hasModule` is returning `true` even when is not running in a NodeJS environment.
```
if (hasModule) {
        module.exports = numbro;

        // Load all languages
        var fs = require('fs'),
            path = require('path');
        var langFiles = fs.readdirSync(path.join(__dirname, 'languages'));
        langFiles.forEach(function (langFile) {
            numbro.language(path.basename(langFile, '.js'), require(path.join(__dirname, 'languages', langFile)));
        });
    }
```

Note:

I am using Browserify v10.2.4.
numbro 1.5.0

Thanks!

**Comment by montogeek** [comment]
After downgrading it to 1.1.1, the initial version that I installed the problem was gone.
Investigating I found that this commit introduced that code https://github.com/foretagsplatsen/numbro/commit/8ca2bec12cf7509ec6fb6734ffc83a4e247f69c6

**Comment by BenjaminVanRyseghem** [comment]
Thanks

We have to fix the `hasModule` as now it's more `isRunningInNode`

:smile:

**Comment by montogeek** [comment]
What if we make language files as modules?

**Comment by BenjaminVanRyseghem** [comment]
I think it's already the case.
But it can be a bit boring to load all the languages this way

**Comment by BenjaminVanRyseghem** [comment]
can you check that #101 fixes this issue?
