### ISSUE TITLE
the currency symbol is $ which is a currency symbol already by itself (the dollar..)

### ISSUE THREAD

**Issue by jcompagner** [foretagsplatsen/numbro#72]
This gives us the problem that if we are in a euro country but we want to say the current number is in dollars we can't just format it like that

$ 00.00 will be come a euro number

Java for example has a special currency sign that is not by itself a currency symbol of any country. This way i can specify a format with a $ and that is then seen as that a plain literal that should just be in that place not replaced with anything.

So is there now a way to escape the $ sign so that it really just keeps that?

This is then also more of a question that we should have pure literal support so the format can be:

£ 00.00
$ 00.00
¥ 00.00

if we really want to show a certain or specifc currency and not just translate it automatically

**Comment by BenjaminVanRyseghem** [comment]
if you want the currency to be in USD, why not changing the numbro language to `en-US`?

**Comment by jcompagner** [comment]
no because that changes also the decimal point or grouping stuff
The language is in for example "nl" (dutch) but we know that we display numbers here that are in dollars and we want to format it like that 

The thing is that on any website you can just easily say i want to see it in this currency or see conversions already on one screen of multiply currencies. its not always that you want to push the currency sign for that specific language.

thats the reason for example in java: http://docs.oracle.com/javase/7/docs/api/java/text/DecimalFormat.html
the currency sign is not an existing currency symbol

**Comment by BenjaminVanRyseghem** [comment]
I am confused

If you want to format number the dutch way, why putting a $ sign?

If you want to force the currency sign, I would suggest you to hardcode it in a separate div, and then just format the value as a number

**Comment by jcompagner** [comment]
yes that can be but thats now how people use our tool. they can set a format (with any literal if needed back and front but thats another thing) and because of that they can just hard code they really want a $ in front of the number. 

This is because the format they follow is the one from http://docs.oracle.com/javase/7/docs/api/java/text/DecimalFormat.html

So what we do is convert the currency symbol of that to the $ sign and then it works for the currency except if we really want the dollar sign (so they have the $ sign in the format which is not a special formatting char, its just a literal that should stay there)

**Comment by BenjaminVanRyseghem** [comment]
I understand but I am still not understanding why you would like to be able to mix a currency with a completely not related value format.
