### ISSUE TITLE
ability to "pad" a number in formatting

### ISSUE THREAD

**Issue by atuttle** [foretagsplatsen/numbro#76]
See also: https://github.com/adamwdraper/Numeral-js/issues/123

Which references this implementation: https://gist.github.com/resident-uhlig/7906919

I don't love the syntax `#N#` but at least it works!

**Comment by fhackenberger** [comment]
@BenjaminVanRyseghem Continuing here, would you mind pulling this and tagging a new release?

**Comment by BenjaminVanRyseghem** [comment]
as @atuttle was saying the syntax is not so nice, so I was thinking about introducing two new functions to the numbro object `padLeft` and `padRight`, what do you guys think?

**Comment by atuttle** [comment]
FWIW, I've worked with other languages/libraries that use the number of digits in the format string as if they were significant-digits; so:

```
5.format('000')
=> 005

15.format('000,000.00')
=> 000,015.00
```

IMO that would be the best possible implementation (seems very clean to me) but I'm not sure how feasible it is to work that into the current formatting implementation, or if it would break any existing expectations at all.

**Comment by BenjaminVanRyseghem** [comment]
Unfortunately that would break a lot of things currently :confused:

**Comment by atuttle** [comment]
What's the supported syntax? From the tests included in that commit it seems that maybe my last suggested syntax (all digits in format string are significant) could be it?

**Comment by BenjaminVanRyseghem** [comment]
That's indeed the case.

I will add documentation with the next release.

But if you want to propose a PR before, feel free :smile:
