### ISSUE TITLE
Why is 0 formatted as +0?

### ISSUE THREAD

**Issue by marceloverdijk** [foretagsplatsen/numbro#78]
var string = numbro(-1).format('+0,0');
    // '-1'

    var string = numbro(1).format('+0,0');
    // '+1'

    var string = numbro(0).format('+0,0');
    // '+0'

The last one I would expect just `0` without a `+` prefixed.

**Comment by BenjaminVanRyseghem** [comment]
I tend to disagree as you are forcing the sign to be displayed :smile:

**Comment by marceloverdijk** [comment]
How would I then configure to only display a + for 'real' positive numbers (not 0 :-))

**Comment by BenjaminVanRyseghem** [comment]
I have no idea :stuck_out_tongue:

**Comment by marceloverdijk** [comment]
Haha :-)

**Comment by clayzermk1** [comment]
I'm going to take a stab at this.

**Comment by marceloverdijk** [comment]
Thanks! I guess this will be part of 1.5.1?

**Comment by BenjaminVanRyseghem** [comment]
@marceloverdijk indeed

I will see if I can update today :wink:

**Comment by marceloverdijk** [comment]
Would be great :thumbsup:

**Comment by BenjaminVanRyseghem** [comment]
In numbro 1.5.1

**Comment by marceloverdijk** [comment]
Created issue on CDNJS to publish there: https://github.com/cdnjs/cdnjs/issues/5307

**Comment by BenjaminVanRyseghem** [comment]
good :smile:

but 1.5.0 is not in CDNjs, there is like 7 versions missing there :panda_face:

**Comment by marceloverdijk** [comment]
https://cdnjs.cloudflare.com/ajax/libs/numbro/1.5.0/numbro.min.js seems to work...

**Comment by BenjaminVanRyseghem** [comment]
good to know ;)
