### ISSUE TITLE
Rescueing lost history

### ISSUE THREAD

**Issue by uniphil** [foretagsplatsen/numbro#8]
First, thanks for forking and maintaining `numeral-js`! Nice to see the PRs from numeral finally getting merged!

However, I think your current fork has lost a lot of important history:

 * The git history is gone.
     * I can't see what changes were made compared to the original `numeral-js` (all that shows up is the rename and a bunch of version bumps when I look through the commits). I almost abandoned this fork entirely because it didn't look like it brought any improvements at all.
     * The git history also provides valuable documentation when browsing the source code and searching for bugs.
 * The changelog is gone.
      * Changelogs are useful when assessing a project to get a sense of how its API evolves, how the authors treat version changes, and more. It would be nice if we didn't lose it!
      * It's a great place to document all the fixes to `numeral-js` that have been made.

Also, since this project is a fork, continuing where development on `numeral-js` left off, I would propose numbering releases where `numeral-js` left off as well, so the first `numbro` release could be `v0.6.0`. That would fit nicely with the original changelog, and make the upgrade path from `numeral-js` easier to see.

----

I went ahead and rebased all of the `numbro` commits onto the end of [your `numeral-js` fork](https://github.com/foretagsplatsen/Numeral-js), keeping the changelog and updating the version to `v1.6.0`. It's [here](https://github.com/uniphil/numbro/tree/master-with-history) (in the `master-with-history` branch).

Check out [the full commit history](https://github.com/uniphil/numbro/commits/master-with-history)

I can't pull-request it, because, since I rebased everything onto the `numeral-js` fork, there's no common history :)

So, my proposal is that you `reset --hard` my rebased fork, `push --force` it to the `numbro` repo here, push v1.6.0 to npm, and roll from there.

I'd love any feedback or other ideas for how we could keep the project's valuable history! :)

**Comment by BenjaminVanRyseghem** [comment]
I like your proposal to have the complete history.

But I would like to keep the numeral changelog separated, as it's a different project now,
and have a new changelog for numbro.

What do you think?

**Comment by uniphil** [comment]
Great!

Good idea to make the `numeral-js` clearly distinct. I moved it to a file called `CHANGELOG-Numeraljs.md` (to follow your `LICENSE-Numeraljs` convention). It's on a branch called [`master-with-history-new-changelog`](https://github.com/uniphil/numbro/tree/master-with-history-new-changelog).

Is that what you had in mind?

**Comment by BenjaminVanRyseghem** [comment]
I would rather have the changelog in a separate `CHANGELOG` file.
I always have the feeling it's burdening the readme file with some "not that important" info :smile:

Also, I keep the current versionning (aka `1.0.4`)

**Comment by uniphil** [comment]
Ok, re-re-rebased, still at [`master-with-history-new-changelog`](https://github.com/uniphil/numbro/tree/master-with-history-new-changelog).

Looks good?

**Comment by BenjaminVanRyseghem** [comment]
Looks good ;)

I will have another look tomorrow after sleeping a bit :smile: and discuss the `push --force` on master (which is always tricky :smile_cat: ) with the other maintainers.

Thanks a lot

**Comment by uniphil** [comment]
Sounds good! Glad to help.

Yeah, I was hoping it would be early enough in this repo's lifetime that you'd consider rewriting history on `master` -- once it's been out for a while and people have cloned, forked, etc. that gets tricky.

**Comment by Graham42** [comment]
+1 for keeping history!

**Comment by Graham42** [comment]
We should also do this for gh-pages branch, I've done th rebase work here https://github.com/Graham42/numbro/tree/gh-pages-with-history

**Comment by BenjaminVanRyseghem** [comment]
Done :+1:

Thanks @uniphil and @Graham42

**Comment by uniphil** [comment]
Awesome! :cake:
