### ISSUE TITLE
Avoid abbreviations in currencies

### ISSUE THREAD

**Issue by whimzi** [foretagsplatsen/numbro#92]
Hi,

I'm using currencies based on languages. It's pretty great but i dont need abbreviations (1k, 1m), i want full numbers. Is it possible to configure that way (with an option) ? I use all availables languages and I dont want to override all existing languages :(

Thanks for your great lib !
Cheers,

Whimzi

**Comment by BenjaminVanRyseghem** [comment]
can you please tell me the format string you use?

**Comment by whimzi** [comment]
None, i use predefined rules

I use numbro.language(xx) where xx is dynamic
and numbro(amount).formatCurrency()

numbro(1003).formatCurrency() -> 1k€ in french

**Comment by BenjaminVanRyseghem** [comment]
then you will have to use `numbro(1003).formatCurrency(',0000')`

**Comment by whimzi** [comment]
Thanks, it works !
I'll use ,0.00
